/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\Administrator\\AppData\\Roaming\\nvm\\v16.15.0\\node_modules\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-3de1a8a0",
    path: "/study/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3de1a8a0").then(next)
    },
  },
  {
    path: "/study/index.html",
    redirect: "/study/"
  },
  {
    name: "v-28e06fe7",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28e06fe7").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-33b80607",
    path: "/study/TS/%E5%9F%BA%E7%A1%80%E7%B1%BB%E5%9E%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33b80607").then(next)
    },
  },
  {
    path: "/study/TS/基础类型.html",
    redirect: "/study/TS/%E5%9F%BA%E7%A1%80%E7%B1%BB%E5%9E%8B.html"
  },
  {
    path: "/study/TS/基础类型.html",
    redirect: "/study/TS/%E5%9F%BA%E7%A1%80%E7%B1%BB%E5%9E%8B.html"
  },
  {
    name: "v-76a5c550",
    path: "/study/math/math1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76a5c550").then(next)
    },
  },
  {
    name: "v-679f0c34",
    path: "/study/TS/test2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-679f0c34").then(next)
    },
  },
  {
    name: "v-7a33f10e",
    path: "/study/math/math2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a33f10e").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]