/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "前端乐园",
  "description": "牛魔王的博客",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/lufi.jpg",
        "heroText": "前端记录",
        "tagline": "一点一滴都是进步",
        "actionText": "马上进入 →",
        "actionLink": "/study/TS/基础类型",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-28e06fe7",
      "path": "/",
      "lastUpdated": "7/26/2022, 3:24:05 PM",
      "lastUpdatedTimestamp": 1658820245000
    },
    {
      "frontmatter": {},
      "regularPath": "/study/TS/%E5%9F%BA%E7%A1%80%E7%B1%BB%E5%9E%8B.html",
      "relativePath": "study/TS/基础类型.md",
      "key": "v-33b80607",
      "path": "/study/TS/%E5%9F%BA%E7%A1%80%E7%B1%BB%E5%9E%8B.html",
      "headers": [
        {
          "level": 3,
          "title": "1.字符串类型",
          "slug": "_1-字符串类型"
        },
        {
          "level": 3,
          "title": "2.数字类型",
          "slug": "_2-数字类型"
        },
        {
          "level": 3,
          "title": "3.布尔类型",
          "slug": "_3-布尔类型"
        },
        {
          "level": 3,
          "title": "4.空值类型",
          "slug": "_4-空值类型"
        },
        {
          "level": 3,
          "title": "5.Null和undefined类型",
          "slug": "_5-null和undefined类型"
        }
      ],
      "lastUpdated": "7/26/2022, 4:08:34 PM",
      "lastUpdatedTimestamp": 1658822914000
    },
    {
      "title": "1、any类型",
      "frontmatter": {},
      "regularPath": "/study/TS/%E4%BB%BB%E6%84%8F%E7%B1%BB%E5%9E%8B.html",
      "relativePath": "study/TS/任意类型.md",
      "key": "v-5d801439",
      "path": "/study/TS/%E4%BB%BB%E6%84%8F%E7%B1%BB%E5%9E%8B.html",
      "headers": [
        {
          "level": 3,
          "title": "1、any类型",
          "slug": "_1、any类型"
        },
        {
          "level": 3,
          "title": "2、unknown 类型",
          "slug": "_2、unknown-类型"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/study/math/math2.html",
      "relativePath": "study/math/math2.md",
      "key": "v-7a33f10e",
      "path": "/study/math/math2.html",
      "lastUpdated": "7/26/2022, 3:24:05 PM",
      "lastUpdatedTimestamp": 1658820245000
    },
    {
      "frontmatter": {},
      "regularPath": "/study/math/math1.html",
      "relativePath": "study/math/math1.md",
      "key": "v-76a5c550",
      "path": "/study/math/math1.html",
      "lastUpdated": "7/26/2022, 3:24:05 PM",
      "lastUpdatedTimestamp": 1658820245000
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "指南",
        "link": "/guide/"
      },
      {
        "text": "生活",
        "link": "/life/"
      },
      {
        "text": "学习",
        "items": [
          {
            "text": "数学",
            "link": "/study/math/math1"
          }
        ]
      }
    ],
    "sidebar": {
      "/study/": [
        {
          "title": "TS",
          "collapsable": true,
          "children": [
            {
              "title": "基础类型",
              "path": "/study/TS/基础类型"
            },
            {
              "title": "任意类型",
              "path": "/study/TS/任意类型"
            }
          ]
        },
        {
          "title": "其他",
          "collapsable": true,
          "children": [
            {
              "title": "阿松大",
              "path": "/study/math/math1"
            }
          ]
        }
      ]
    },
    "sidebarDepth": 2,
    "lastUpdated": "Last Updated"
  }
}